{ fetchFromGitHub }:

# This is autogenerated through util/gen.hs
{
  http-client = fetchFromGitHub {
    owner = "snoyberg";
    repo = "http-client";
    rev = "1a75bdfca014723dd5d40760fad854b3f0f37156";
    sha256 = "q2GIAB4lNda8G/C6XnbN38/Zz9ZcK2gO3fCvNKFcZxQ=";
  };
  cardano-wallet = fetchFromGitHub {
    owner = "j-mueller";
    repo = "cardano-wallet";
    rev = "6be73ab852c0592713dfe78218856d4a8a0ee69e";
    sha256 = "5IZuqlE/4aGH3TEuGYQsZwOpI/Q7DYzJ4q3stuqGpWc=";
  };
  servant-purescript = fetchFromGitHub {
    owner = "input-output-hk";
    repo = "servant-purescript";
    rev = "ebea59c7bdfc0338d83fca772b9a57e28560bcde";
    sha256 = "VkM9Q2XkDEnQh6khptoIjQ9xW7Fc2wsOJ4vPYDzBTD4=";
  };
  purescript-bridge = fetchFromGitHub {
    owner = "input-output-hk";
    repo = "purescript-bridge";
    rev = "366fc70b341e2633f3ad0158a577d52e1cd2b138";
    sha256 = "paaId4GJ9/Z5LstYfakiCJZ2p9Q5NMHXdXUx5rTPQKI=";
  };
  plutus-apps = fetchFromGitHub {
    owner = "input-output-hk";
    repo = "plutus-apps";
    rev = "a6868cde87600051a4cc808777d665d0b859853c";
    sha256 = "thC2pEsZSnc2co9keNsdmMnXr9NzaLn9t9fKqWx9oII=";
  };
  plutus = fetchFromGitHub {
    owner = "input-output-hk";
    repo = "plutus";
    rev = "3f089ccf0ca746b399c99afe51e063b0640af547";
    sha256 = "BhGQPiCv4UxVs0XEdMMddaNWiztmkoeJotpW/lrtqNs=";
  };
  ouroboros-network = fetchFromGitHub {
    owner = "input-output-hk";
    repo = "ouroboros-network";
    rev = "1f4973f36f689d6da75b5d351fb124d66ef1057d";
    sha256 = "lwTgyoZBQAaU6Sh7BouGJGUvK1tSVrWhJP63v7MpwKA=";
  };
  optparse-applicative = fetchFromGitHub {
    owner = "input-output-hk";
    repo = "optparse-applicative";
    rev = "7497a29cb998721a9068d5725d49461f2bba0e7a";
    sha256 = "uQx+SEYsCH7JcG3xAT0eJck9yq3y0cvx49bvItLLer8=";
  };
  iohk-monitoring-framework = fetchFromGitHub {
    owner = "input-output-hk";
    repo = "iohk-monitoring-framework";
    rev = "46f994e216a1f8b36fe4669b47b2a7011b0e153c";
    sha256 = "QE3QRpIHIABm+qCP/wP4epbUx0JmSJ9BMePqWEd3iMY=";
  };
  hedgehog-extras = fetchFromGitHub {
    owner = "input-output-hk";
    repo = "hedgehog-extras";
    rev = "edf6945007177a638fbeb8802397f3a6f4e47c14";
    sha256 = "KYLGLpDGHWlb/Gcx6Q/2HTnRMzZQmPKz0JbIw+bHh3E=";
  };
  goblins = fetchFromGitHub {
    owner = "input-output-hk";
    repo = "goblins";
    rev = "cde90a2b27f79187ca8310b6549331e59595e7ba";
    sha256 = "z9ut0y6umDIjJIRjz9KSvKgotuw06/S8QDwOtVdGiJ0=";
  };
  ekg-forward = fetchFromGitHub {
    owner = "input-output-hk";
    repo = "ekg-forward";
    rev = "d9e8fd302fa6ba41c07183d371e6777286d37bc2";
    sha256 = "kwpX1GBd6UMB8sC9vJF06mMr0CbNn3ykRKLEgSFdDGk=";
  };
  cardano-sl-x509 = fetchFromGitHub {
    owner = "input-output-hk";
    repo = "cardano-sl-x509";
    rev = "12925934c533b3a6e009b61ede555f8f26bac037";
    sha256 = "8XwEtSnhl5f89O10wFyT2+yqvTtKwqjfHdVQjV4Rqs4=";
  };
  cardano-prelude = fetchFromGitHub {
    owner = "input-output-hk";
    repo = "cardano-prelude";
    rev = "fd773f7a58412131512b9f694ab95653ac430852";
    sha256 = "BtbT5UxOAADvQD4qTPNrGfnjQNgbYNO4EAJwH2ZsTQo=";
  };
  cardano-node = fetchFromGitHub {
    owner = "input-output-hk";
    repo = "cardano-node";
    rev = "b6ca519f97a0e795611a63174687e6bb70c9f752";
    sha256 = "tuEtSCJOk1MA9sguxL13XLa+qHaz//v7eNyhxHC9tHw=";
  };
  cardano-ledger-specs = fetchFromGitHub {
    owner = "input-output-hk";
    repo = "cardano-ledger-specs";
    rev = "bf008ce028751cae9fb0b53c3bef20f07c06e333";
    sha256 = "HTPOmVOXgBD/3uAxZip/HSttaKcJ+uImYDbuwANAw1c=";
  };
  cardano-crypto = fetchFromGitHub {
    owner = "input-output-hk";
    repo = "cardano-crypto";
    rev = "07397f0e50da97eaa0575d93bee7ac4b2b2576ec";
    sha256 = "oxIOVlgm07FAEmgGRF1C2me9TXqVxQulEOcJ22zpTRs=";
  };
  cardano-base = fetchFromGitHub {
    owner = "input-output-hk";
    repo = "cardano-base";
    rev = "4ea7e2d927c9a7f78ddc69738409a5827ab66b98";
    sha256 = "zbjq43Bnhv1/LhJCFlI8gdd61dGvVlkEa6wkCvLqEFg=";
  };
  cardano-addresses = fetchFromGitHub {
    owner = "input-output-hk";
    repo = "cardano-addresses";
    rev = "d2f86caa085402a953920c6714a0de6a50b655ec";
    sha256 = "XgXQKJHRKAFwIjONh19D/gKE0ARlhMXXcV74eZpd0lw=";
  };
  Win32-network = fetchFromGitHub {
    owner = "input-output-hk";
    repo = "Win32-network";
    rev = "3825d3abf75f83f406c1f7161883c438dac7277d";
    sha256 = "Hesb5GXSx0IwKSIi42ofisVELcQNX6lwHcoZcbaDiqc=";
  };
  flat = fetchFromGitHub {
    owner = "Quid2";
    repo = "flat";
    rev = "ee59880f47ab835dbd73bea0847dab7869fc20d8";
    sha256 = "lRFND+ZnZvAph6ZYkr9wl9VAx41pb3uSFP8Wc7idP9M=";
  };
}
